openapi: 3.0.3

info:
  version: "0.0.5"
  description: |
    ## SalesKit Webview에 제공하는 Android/iOS Native 함수 목록
    ***
    ## web(js)에서 현재 Android App인지 iOS App인지 판단하는 방법
    - ```navigator.useragent``` 변수로 확인 가능 (콘솔로 찍어볼 수 있음)
      - ```saleskit_android_app```
      - ```saleskit_ios_app```
    ## web(js)에서 호출법
    - Android: ```window.WebInterface.함수이름( JSON.stringify(Object) );```
    
    - iOS: ```window.webkit.messageHandlers.함수이름.postMessage( JSON.stringify(Object) );```
    ## web(js)에서 응답받기
    - Android, iOS: ```responseNative(Object)```
      ### 성공 Object 예시 (ok: Boolean, data: Object?)
      ```
      {
        "ok": true,
        "data": {
          "testData": "테스트데이터입니다."
        }
      }
      ```
      ### 실패 Object 예시 (ok: Boolean, message: String?)
      ```
      {
        "ok": false,
        "message": "process failed"
      }
      ```
      - Object? 와 String? 은 해당변수가 없을 수도 있다는 뜻.
    ***
    ## 참고
    - Swagger 문법에 맞추기 위해 모든 API가 POST로 되어 있음
    - 일반적으로 제공되는 함수의 Parameter는 String(json)
    - Request Body 부분이 해당 함수의 Parameter는 String(json)이다.
  title: SalesKit Webview Bridge
#tags:
#  - name: CAMERA

paths:

  /testAPI:
    post:
      tags:
        - 공통 API
      summary: 테스트 API 호출
      operationId: testAPI
      description: 사용법 - testAPI( { true, 2 } )  =>  2초 후에 참 호출됨
      parameters:
        - name: json
          in: object
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RequestTestAPI'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTestAPI200'
        '400':
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseTestAPI400'

  /contactsExtraction:
    post:
      tags:
        - 공통 API
      summary: 주소록 추출 호출
      operationId: contactsExtraction
      description: 사용법 - contactsExtraction( { } )  =>  주소록 추출 호출 됨.
      parameters:
        - name: json
          in: object
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseContactsExtraction200'
        '400':
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseContactsExtraction400'

  /getCameraPermission:
    post:
      tags:
        - 공통 API
      summary: 카메라 권한 획득 호출
      operationId: getCameraPermission
      description: 사용법 - getCameraPermission( { } )  =>  카메라 권한 획득 호출 됨.
      parameters:
        - name: json
          in: object
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetCameraPermission200'
        '400':
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetCameraPermission400'

  /getAppVersion:
    post:
      tags:
        - 공통 API
      summary: 앱 버전 호출
      operationId: getAppVersion
      description: 사용법 - getAppVersion( { } )  =>  앱 버전 호출 됨.
      parameters:
        - name: json
          in: object
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetAppVersion200'
        '400':
          description: FAIL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseGetAppVersion400'




components:
  schemas:

    ResponseContactsExtraction200:
      type: object
      properties:
        ok:
          type: boolean
          example: true
          description: API 완료 여부
        data:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                example: 홍길동
              phoneNumber:
                type: string
                example: "01012345678"
              org:
                type: string
                example: 인지소프트
              title:
                type: string
                example: 프로
          description: 데이터 목록
      required:
        - ok

    ResponseContactsExtraction400:
      type: object
      properties:
        ok:
          type: boolean
          example: false
          description: API 완료 여부
        message:
          type: string
          example: "process failed"
      required:
        - ok


    RequestTestAPI:
      type: object
      properties:
        bool:
          type: boolean
          example: true
          description: Boolean 값
        second:
          type: integer
          example: 2
          description: 숫자 값
      required:
        - bool

    ResponseTestAPI200:
      type: object
      properties:
        ok:
          type: boolean
          example: true
          description: API 완료 여부
        data:
          type: object
          properties:
            test1:
              type: boolean
              example: true
              description: 테스트 1
            test2:
              type: string
              example: "trueString~~"
              description: 테스트 2
          description: 데이터
      required:
        - ok
        - data

    ResponseTestAPI400:
      type: object
      properties:
        ok:
          type: boolean
          example: false
          description: API 완료 여부
        message:
          type: string
          example: "falseMessage~~~~~"
      required:
        - ok
        - message


    ResponseGetCameraPermission200:
      type: object
      properties:
        ok:
          type: boolean
          example: true
          description: API 완료 여부
      required:
        - ok
        - data

    ResponseGetCameraPermission400:
      type: object
      properties:
        ok:
          type: boolean
          example: false
          description: API 완료 여부
      required:
        - ok
        - message


    ResponseGetAppVersion200:
      type: object
      properties:
        ok:
          type: boolean
          example: true
          description: API 완료 여부
        data:
          type: object
          properties:
            os:
              type: string
              example: "android"
              description: 앱 os
            version:
              type: string
              example: "0.0.1"
              description: 앱 버전
          description: 데이터
      required:
        - ok
        - data

    ResponseGetAppVersion400:
      type: object
      properties:
        ok:
          type: boolean
          example: false
          description: API 완료 여부
      required:
        - ok
        - message
